### PR TITLE
feat : Toogle bar activate and dectiavted button is implements

### PR DESCRIPTION
**Pull request by ekram2d**
GuestLookUp components there  Toogle bar activate and dectiavted button is implements

### CODE REVIEW

**Review by ahmad-ml — CHANGES_REQUESTED** [review]
active button acting as deactivate. 

Toggle button color choice needs to improve

**Review by ahmad-ml — CHANGES_REQUESTED** [review]
active button acting as deactivate. 

Toggle button color choice needs to improve

**Comment by ekram2d** [comment]
sir i change the code as your requirements, please checks new code.

**Comment by ekram2d** [comment]
image
i also implement this pages and print options please check the Booking booking-overview

**Comment by ahmad-ml** [comment]
> image i also implement this pages and print options please check the Booking booking-overview

Thanks. But the print version is not good.

**Pull request closed without merging**
