### PR TITLE
feat: implement toggle button for show the active and deactived info

### PR DESCRIPTION
**Pull request by Bishal-Arman**
implement toggle button

### CODE REVIEW

**Review by ahmad-ml — CHANGES_REQUESTED** [review]
Not working.

**Comment by Bishal-Arman** [comment]
> Not working.

sir,i have fixed the problem...please check again and review..thank you sir

**Review by ahmad-ml — CHANGES_REQUESTED** [review]
Just sort has some issue. Other than all ok. 

One more issue. The guest should lookup only customer category

**Review by ahmad-ml — CHANGES_REQUESTED** [review]
Just sort has some issue. Other than all ok. 

One more issue. The guest should lookup only customer category

**Pull request closed without merging**
