### PR TITLE
Added Guest Booking overview Modal at Guest Look up to see guest booking details.

### PR DESCRIPTION
**Pull request by pieash9**
Showing Guest Booking info
image

### CODE REVIEW

**Comment by ahmad-ml** [comment]
image


the hyper link is not working .. @pieash9

**Comment by pieash9** [comment]
@ahmad-ml  hyperlink is now working sir.

**Comment by ahmad-ml** [comment]
did you made any commit again ?

**Comment by pieash9** [comment]
yes sir.

**Pull request merged**
