### PR TITLE
feat: private route created for ADMIN and STAFF  ,  Booking Overview page and print functionality  implements 

### PR DESCRIPTION
**Pull request by ekram2d**
#private route created for staff
image

#Booking overview page implement 
image

#Print and download features implement 
image

### CODE REVIEW

**Comment by annur-nifty** [comment]
Very good, All the things are checked and totally works fine as well

**Comment by ekram2d** [comment]
> Very good, All the things are checked and totally works fine as well

thank you  [annur-nifty](https://github.com/annur-nifty) vai

**Comment by annur-nifty** [comment]
- Just refetch when we add employees on the fly changes, try to fix issue

**Comment by ekram2d** [comment]
> * Just use refetch when we add employees on the fly changes, try to fix issue

where i use refetch,i am not clear,room everveiw  there are no update functionality

**Comment by annur-nifty** [comment]
well done

**Pull request closed without merging**
