### PR TITLE
feat:Employee deatails show with transaction and input field muted 

### PR DESCRIPTION
**Pull request by Bishal-Arman**
#If any more functionality is required please let me know....

feat:Employee deatails on click more button show the popup and show with transaction and input field muted

### CODE REVIEW

**Comment by Bishal-Arman** [comment]
#search implementation
search

**Comment by Bishal-Arman** [comment]
#If any more functionality is required please let me know....

**Comment by annur-nifty** [comment]
## Added refetch query for on-the-fly changes when we create employees
## well done @Bishal-Arman

**Comment by Bishal-Arman** [comment]
> ## Added refetch query for on-the-fly changes when we create employees
> ## well done @Bishal-Arman 
## Thank you sir

**Pull request merged**
